# Generated by Django 5.2.14 on 2026-05-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='protein',
            field=models.IntegerField(default=0),
        ),
    ]
