# Generated by Django 5.2.14 on 2026-05-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_meal_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(default='Meal', max_length=50),
        ),
    ]
