# Generated by Django 6.0.3 on 2026-06-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_meal_meal_time_meal_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
