# Generated by Django 5.2.14 on 2026-06-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_meal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bmi_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
